### ISSUE TITLE
[Improvement] Shared bucket for etcd backup for the clusters

### ISSUE THREAD

**Issue by PadmaB** [gardener/etcd-backup-restore#141]
# Improvement
As an operator, I would like to efficiently use the backup bucket for multiple clusters, thereby limiting the total number of buckets required.

# Motivation
Currently, every shoot cluster has its own etcd backup bucket with a centrally configured retention period. With the growing number of clusters, we are soon running out of the quota limits of buckets on the cloud provider. Moreover, even if the clusters are deleted, the backup buckets do exist, for a configured period of retention

# Options
[ ] Reduce the retention period or make it configurable [ofcourse, within controlled limits]
[ ] Ability to switch of the backup functionality for certain clusters, ex: our own e2e test clusters
[ ] Shared bucket - for ex: one per seed or one per set of shoots

# Tasks
[ ] Extension Controller per provider + Tests
[ ] Gardener integration + Tests
[ ] Migration of buckets to the shared bucket model

# Acceptance Criteria
[ ] Should be able to share bucket for backup by multiple shoot clusters

# Definition of Done 
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit tests are provided: Have you written automated unit tests?
- [ ] Integration tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you updated the READMEs/docs/how-tos about user-relevant changes?
