### ISSUE TITLE
[Improvement] Switch to Storage Class to SSD from the default

### ISSUE THREAD

**Issue by PadmaB** [gardener/etcd-backup-restore#142]
# Improvement
As an operator for better IOPS and throughput, I would like to the storageclass to SSD instead of the default type.
**Note:** The switch should ensure minimal downtime. 

# Options
[ ] Use SSD as the default StorageClass for the Seed Clusters
[ ] Use SSD as the default StorageClass for the Shoot Clusters or make it configurable allowing the consumers to make their choice [can be picked up in long-term] 

# Tasks
[ ] Finalize the StorageClass for each of the Cloud Providers
[ ] End-to-End testing before making a release 

# Acceptance Criteria
[ ] SSD is used as the default StorageClass for the Seed Clusters  

# Definition of Done 
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit tests are provided: Have you written automated unit tests?
- [ ] Integration tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you updated the READMEs/docs/how-tos about user-relevant changes?
