### ISSUE TITLE
Deploy VPA for etcd backup and restore

### ISSUE THREAD

**Issue by PadmaB** [gardener/etcd-backup-restore#144]
# Story
As an administrator, I would like to deploy VPA for etcd-backup-restore and make use of its recommendations to be able to manage larger clusters 

# Tasks
- [x] Deploy VPA for ETCD with the updater set to 'off' mode
- [x] Create the necessary grafana dashboard showing actual vs recommended metrics
- [ ] Based on the observation, switch the VPA Updater to mode 'initial' 

# Acceptance Criteria
- [x] Observe the recommendations of VPA for etcd-backup-restore
- [ ] Adapt VPA recommendations by switching the VPA Updater to 'initial' or as appropriate

**Comment by PadmaB** [comment]
There is a separate issue [#145](https://github.com/gardener/etcd-backup-restore/issues/145) to switch the mode of VPA for ETCD as required. Closing this issue
