### ISSUE TITLE
Scaling recommendations for single-node ETCD for larger Kubernetes clusters

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/etcd-backup-restore#64]
### Story

* As a [Gardener](https://github.com/gardener/gardener) user, I want to create larger Kubernetes shoot clusters with ~500 to 1000 nodes and the ETCD back-end should support the corresponding load.
* As a [Gardener](https://github.com/gardener/gardener) administrator, I want recommendations about scaling parameters for ETCD that can support larger Kubernetes clusters.

### Motivation

* An ETCD instance with 2.5G RAM (as is currently provisioned by [Gardener](https://github.com/gardener/gardener)) can barely support a Kubernetes cluster with ~130 nodes served by 6 `kuber-apiserver` replicas. 
* Memory and CPU are not the only parameters to be considered during the scaling.
Above 6 replicas of `kube-apiserver`, disk or network IO also could be a bottleneck. This can be seen in the [metrics](https://github.com/gardener/etcd-backup-restore/files/2574704/etcd_metrics.txt) recorded for the above scenario.

### Acceptance Criteria

- [ ] Evaluate and recommend CPU, memory, disk/network IO, ETCD configurations to be able to support larger Kubernetes clusters. At least 500 nodes if not 1000.

- [ ] Recommendations should include the recommendations for the backup-restore sidecar as well to handle larger backups (1.5-2G)

- [ ] Integrate the above recommendation with [Gardener](https://github.com/gardener/gardener).

**Comment by PadmaB** [comment]
#109
